name: Publish to NPM

on:
  push:
    branches: 
      -   master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}
      - run: git fetch --tags
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build:modules
      - run: npm run build:css
      - run: npm run build:write-types
      # after writing  back types, also commit them
      - name: Git Auto Commit type changes
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
      - run: npm run lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
